import { CreditRequestProps } from "@/domain/entities/CreditRequest";
import { Money } from "@/domain/value-objects/Money";

// Helper that reconstructs a CreditRequestProps object with Money instances
// stored as plain numbers in JSON – we persist .value and rehydrate here
export function makeMockRequest(raw: Omit<CreditRequestProps, "valorSolicitado" | "valorAprovado"> & {
  valorSolicitado: number;
  valorAprovado?: number;
}): CreditRequestProps {
  return {
    ...raw,
    valorSolicitado: Money.fromReais(raw.valorSolicitado),
    valorAprovado: raw.valorAprovado != null ? Money.fromReais(raw.valorAprovado) : undefined,
  };
}

export const RAW_MOCK_REQUESTS = [
  {
    id: "req-001",
    numeroSolicitacao: "SOL-2026-00001",
    customerId: "cust-001",
    valorSolicitado: 45000,
    bandeiraId: "bandeira-visa",
    modalidade: "CAPITAL_GIRO",
    finalidade: "Expansão de operações",
    status: "APROVADA" as const,
    alcadaRequerida: "COORDENADOR" as const,
    dataInclusao: new Date("2026-03-10"),
    dataConclusao: new Date("2026-03-12"),
    valorAprovado: 45000,
    scoreCredito: 720,
    responsavelAnaliseId: "user-002",
  },
  {
    id: "req-002",
    numeroSolicitacao: "SOL-2026-00002",
    customerId: "cust-002",
    valorSolicitado: 180000,
    bandeiraId: "bandeira-master",
    modalidade: "CREDITO_PARCELADO",
    finalidade: "Aquisição de equipamentos",
    status: "EM_APROVACAO" as const,
    alcadaRequerida: "GERENTE" as const,
    dataInclusao: new Date("2026-04-01"),
    scoreCredito: 680,
    responsavelAnaliseId: "user-003",
  },
  {
    id: "req-003",
    numeroSolicitacao: "SOL-2026-00003",
    customerId: "cust-003",
    valorSolicitado: 8500,
    bandeiraId: "bandeira-visa",
    modalidade: "CREDITO_PESSOAL",
    finalidade: "Reforma residencial",
    status: "SOLICITADA" as const,
    alcadaRequerida: "LIDER" as const,
    dataInclusao: new Date("2026-04-15"),
    scoreCredito: 540,
  },
  {
    id: "req-004",
    numeroSolicitacao: "SOL-2026-00004",
    customerId: "cust-004",
    valorSolicitado: 750000,
    bandeiraId: "bandeira-hipercard",
    modalidade: "FINANCIAMENTO",
    finalidade: "Construção de galpão logístico",
    status: "EM_ANALISE" as const,
    alcadaRequerida: "GERENTE_GERAL" as const,
    dataInclusao: new Date("2026-04-10"),
    scoreCredito: 760,
    responsavelAnaliseId: "user-001",
  },
  {
    id: "req-005",
    numeroSolicitacao: "SOL-2026-00005",
    customerId: "cust-005",
    valorSolicitado: 3200,
    bandeiraId: "bandeira-visa",
    modalidade: "CREDITO_PESSOAL",
    finalidade: "Despesas médicas",
    status: "REJEITADA" as const,
    alcadaRequerida: "LIDER" as const,
    dataInclusao: new Date("2026-04-05"),
    dataConclusao: new Date("2026-04-06"),
    motivoRejeicao: "Score de crédito insuficiente",
    scoreCredito: 380,
  },
  {
    id: "req-006",
    numeroSolicitacao: "SOL-2026-00006",
    customerId: "cust-006",
    valorSolicitado: 95000,
    bandeiraId: "bandeira-master",
    modalidade: "CAPITAL_GIRO",
    finalidade: "Sazonalidade — estoque Q2",
    status: "APROVADA" as const,
    alcadaRequerida: "GERENTE" as const,
    dataInclusao: new Date("2026-04-08"),
    dataConclusao: new Date("2026-04-09"),
    valorAprovado: 90000,
    scoreCredito: 810,
    responsavelAnaliseId: "user-003",
  },
  {
    id: "req-007",
    numeroSolicitacao: "SOL-2026-00007",
    customerId: "cust-001",
    valorSolicitado: 22000,
    bandeiraId: "bandeira-visa",
    modalidade: "CREDITO_PARCELADO",
    finalidade: "Automóvel — frota",
    status: "EM_ANALISE" as const,
    alcadaRequerida: "COORDENADOR" as const,
    dataInclusao: new Date("2026-04-18"),
    scoreCredito: 695,
    responsavelAnaliseId: "user-001",
  },
  {
    id: "req-008",
    numeroSolicitacao: "SOL-2026-00008",
    customerId: "cust-002",
    valorSolicitado: 1200000,
    bandeiraId: "bandeira-hipercard",
    modalidade: "FINANCIAMENTO",
    finalidade: "Aquisição de imóvel comercial",
    status: "SOLICITADA" as const,
    alcadaRequerida: "DIRETORIA" as const,
    dataInclusao: new Date("2026-04-20"),
    scoreCredito: 790,
  },
];
